import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "cbstUmDENc0",
    video_title: "Re-edited a video for Dhruv Rathee",
    video_description: `A prominent YouTuber with millions of subscribers, to enhance its pacing, visual appeal, and storytelling.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "cbstUmDENc0",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/cbstUmDENc0",
    project_images: [],
    category: ["Documentry"],
    duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "bJ6VVhmxefQ",
    video_title: "NBS Pictures",
    video_description:
      "Edited raw footage provided by NBS Pictures, a popular YouTuber, to create a polished and engaging video.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "bJ6VVhmxefQ",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/NBS-Pictures.png",
    client_feedback: "",
    video_link: "https://youtu.be/bJ6VVhmxefQ",
    project_images: [],
    category: ["Shorts", "Reels"],
    duration: "10:12",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "WMtVfUTRE2U",
    video_title:
      "Re-edit @Vox- 3D Reel",
    video_description: `3. re-edited this video & audio is taken from  @Vox`,
    tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
    cover_image: "WMtVfUTRE2U",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/WMtVfUTRE2U",
    project_images: [],
    category: ["Shorts", "Reels"],
    duration: "7:18",
    software_used: ["Davinci Resolve"],
  },
];
